#管道命名
name: CI
#流水线的触发条件：在推送时触发
on: [push]
#添加任务
jobs:
#  扫描任务：bandit
 sast_scan:
#   命名
   name: Run Bandit Scan
#   环境
   runs-on: ubuntu-latest
#   具体步骤
   steps:
#     查看代码
   - name: Checkout code
#     检出代码
     uses: actions/checkout@v2
#   显示安装任务需要的依赖
   - name: Set up Python
     uses: actions/setup-python@v2
#     指定版本
     with:
       python-version: 3.8
#   安装Bandit
   - name: Install Bandit
     run: pip install bandit
#   运行Bandit
   - name: Run Bandit Scan
#     扫描所有文件,仅关注中、高级的风险
     run: bandit -ll -ii -r . -f json -o bandit-report.json
#     上传产物，即检测报告
   - name: Upload Artifact
     uses: actions/upload-artifact@v4
#     无论前序步骤是否成功，都执行
     if: always()
     with:
      name: bandit-findings
#     要上传的文件名
      path: bandit-report.json

#   构建镜像并进行镜像扫描
 image_scan:
   name: Build Image and Run Image Scan
   runs-on: ubuntu-latest
   steps:
   - name: Checkout code
     uses: actions/checkout@v2
#   安装Docker
   - name: Set up Docker
     uses: docker-practice/actions-setup-docker@v1
     with:
      docker_version: '20.10.7'
#   构建镜像
   - name: Build Docker Image
     run: docker build -f Dockerfile -t myapp:latest .

#   调用官方action进行镜像扫描
   - name: Docker Scout Scan
     uses: docker/scout-action@v1.0.9
     with:
#       非硬编码配置docker用户名和密码
       dockerhub-user: ${{ secrets.REPO_USER }}
       dockerhub-password: ${{ secrets.REPO_PWD }}
#       快速查看和扫描漏洞
       command: quickview,cves

